devopcollab/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, IntegerField
from wtforms.validators import DataRequired

status_list=[('Open','Open'),('Withdraw', 'Withdraw'),('Closed', 'Closed')]
devops_owner_list=[('Iron.Man','Iron.Man'),('Captain.American', 'Captain.American'),('Black.Widow', 'Black.Widow')]

class BlogPostForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    title = StringField('Request Title', validators=[DataRequired()])
    text = TextAreaField('Request Content', validators=[DataRequired()])
    status = SelectField('Status', choices=status_list, validators=[DataRequired()] )
    submit = SubmitField('Submit')

class BlogPostFormAdmin(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    title = StringField('Request Title', validators=[DataRequired()])
    text = TextAreaField('Request Content', validators=[DataRequired()])
    status = SelectField('Status', choices=status_list, validators=[DataRequired()] )
    devops_owner = SelectField('DevOps Owner', choices=devops_owner_list, validators=[DataRequired()] )
    effort_hour = IntegerField('DevOps Hour')
    submit = SubmitField('Submit')

devopcollab/blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from devopcollab import db
from devopcollab.models import BlogPost
from devopcollab.blog_posts.forms import BlogPostForm, BlogPostFormAdmin

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():

    if not current_user.is_admin:
        form = BlogPostForm()

        if form.validate_on_submit():

            blog_post = BlogPost(title=form.title.data,
                                text=form.text.data,
                                status=form.status.data,
                                user_id=current_user.id
                                )
            db.session.add(blog_post)
            db.session.commit()
            flash("Blog Post Created")
            return redirect(url_for('core.index'))
    else:
        #is admin
        form = BlogPostFormAdmin(devops_owner='John.Doe',effort_hour=0)
        if form.validate_on_submit():
            blog_post = BlogPost(title=form.title.data,
                                text=form.text.data,
                                status=form.status.data,
                                user_id=current_user.id,
                                devops_owner=form.devops_owner.data,
                                effort_hour=form.effort_hour.data
                                )
            db.session.add(blog_post)
            db.session.commit()
            flash('Post Created by Admin')
            return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


# int: makes sure that the blog_post_id gets passed as in integer
# instead of a string so we can look it up later.
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    # grab the requested blog post by id number or return 404
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )

@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    print('update blog: '+str(blog_post_id)+' by '+ current_user.username + ' is_admin:' + str(current_user.is_admin))
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if not current_user.is_admin and blog_post.author != current_user:
        # Forbidden, No Access
        abort(403)
    if not current_user.is_admin:
        form = BlogPostForm()
        if form.validate_on_submit():
            blog_post.title = form.title.data
            blog_post.text = form.text.data
            blog_post.status = form.status.data
            db.session.commit()
            flash('Post Updated')
            return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
        # Pass back the old blog post information so they can start again with
        # the old text and title.
        elif request.method == 'GET':
            form.title.data = blog_post.title
            form.text.data = blog_post.text
            form.status.data = blog_post.status

    if current_user.is_admin:
        print('admin path.')
        form = BlogPostFormAdmin(devops_owner='John.Doe',effort_hour=0)
        if form.validate_on_submit():
            blog_post.title = form.title.data
            blog_post.text = form.text.data
            blog_post.status = form.status.data
            blog_post.devops_onwer = form.devops_owner.data
            blog_post.effort_hour = form.effort_hour.data
            print('effort_hour: '+ str(form.effort_hour.data))
            db.session.commit()
            flash('Post Updated')
            return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
        # Pass back the old blog post information so they can start again with
        # the old text and title.
        elif request.method == 'GET':
            form.title.data = blog_post.title
            form.text.data = blog_post.text
            form.status.data = blog_post.status
            form.devops_owner.data = blog_post.devops_onwer
            form.effort_hour.data = blog_post.effort_hour if blog_post.effort_hour != None else 0

    return render_template('create_post.html', title='Update',
                           form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

# @blog_posts.route('/api/data')
# def data():
#     return {'data': [user.to_dict() for user in blog_post.query]}

devopcollab/core/views.py
from flask import render_template,request,Blueprint
from devopcollab.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=100)
    return render_template('index.html',blog_posts=blog_posts)
# def index():
#     return render_template('ajax_table.html', title='Ajax Table')

@core.route('/info')
def info():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('info.html')

# @core.route('/user_mgr')
# def info():
#     '''
#     Example view of any other "core" page. Such as a info page, about page,
#     contact page. Any page that doesn't really sync with one of the models.
#     '''
#     return render_template('user_mgr.html')

devopcollab/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from devopcollab import db
from werkzeug.security import generate_password_hash,check_password_hash
from devopcollab.models import User, BlogPost
from devopcollab.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from devopcollab.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

        if user.check_password(form.password.data) and user is not None:
            #Log in the user

            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

devopcollab/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>

</div>

{% endblock content %}

devopcollab/templates/ajax_table.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <h1>devops Request Management</h1>
  {% if current_user.is_authenticated %}
  <p>Welcome, {{current_user.username}}!</p>
  {% else %}
  <p>Welcome, you need to login or register to create request.</p>
  {% endif %} {% if current_user.is_authenticated and current_user.is_admin%}
  <div class="col text-right">
    <button type="button" id="update_repos" class="btn btn-success mybutton">
      Download Table
    </button>
  </div>
  {% endif %}
</div>

<div class="container">
  {# Go through each blog post #}

  <table id="data" class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Created By</th>
        <th>Request Time</th>
        <th>Request Title</th>
        <th>Status</th>
        <th>devops Effort(h)</th>
        <th>devops Owner</th>
      </tr>
    </thead>
    <tbody>
      {% for post in blog_posts.items %}
      <tr>
        <td>{{ post.author.username }}</td>
        <td>{{ post.date.strftime('%Y-%m-%d-%H:%M:%S') }}</td>
        <td>
          <a
            class="card-title"
            href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}"
            >{{ post.title }}</a
          >
        </td>
        <td>{{post.status}}</td>
        <td>{{ post.effort_hour }}</td>
        <td>{{post.devops_owner}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% endblock %} {% block scripts %}
  <script>
    $(document).ready(function () {
      $("#data").DataTable({
        ajax: "/api/data",
        columns: [
          { data: "name" },
          { data: "age", searchable: false },
          { data: "address", orderable: false, searchable: false },
          { data: "phone", orderable: false, searchable: false },
          { data: "email" },
        ],
      });
    });
    $(document).ready(function () {
      $("#data").DataTable({
        order: [[1, "desc"]],
        columns: [
          null,
          { searchable: false },
          { orderable: false },
          null,
          { searchable: false },
          null,
        ],
      });
    });
  </script>
  {% endblock %}
</div>

devopcollab/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <meta charset="utf-8">
  <title></title>

</head>

<body>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top custom-navbar ml-auto">
    <nav class="navbar navbar-dark bg-dark">
      <span class="navbar-brand mb-0 h1">
        devops Request
      </span>
    </nav>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('core.info') }}">How-to</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
        </li>
        {% if current_user.is_admin %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.account') }}">User Management</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('blog_posts.create_post') }}">Create</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.account') }}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-person-circle" viewBox="0 0 16 16">
              <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
              <path fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
            </svg>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.login')}}">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
        </li>
        {% endif %}
      </ul>

      <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
    </div>
  </nav>

  <div class="container">
    {% block content %}

    {% endblock %}
  </div>
  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
  {% block scripts %}{% endblock %}
  <script src="{{url_for('static', filename='master.js')}}"></script>
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/master.css')}}">
  </link>
</body>

</html>

devopcollab/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Created by: {{post.author.username}}</h2>
  <h3>Create Time: {{ post.date.strftime('%H:%M, %B %d, %Y, ') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user or current_user.is_admin %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

devopcollab/templates/create_post.html
{% extends "base.html" %} {% block content %}
<div class="container create-form">
  <form class="form-group" method="POST">
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{ form.title.label(class="col-form-label") }} {{
      form.title(class="form-control",placeholder="Request Title") }}
    </div>
    <div class="form-group">
      {{ form.text.label(class="form-control-label") }} {{
      form.text(class="form-control", placeholder="Write Your Request Content.")
      }}
    </div>
    <div class="form-group">
      {{ form.status.label(class="form-control-label") }} {{
      form.status(class="form-control") }}
    </div>

    {% if current_user.is_admin %}
    <div class="form-group">
      {{ form.devops_owner.label(class="form-control-label") }} {{
      form.devops_owner(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.effort_hour.label(class="form-control-label") }} {{
      form.effort_hour(class="form-control") }}
    </div>
    {% endif %}
    <div class="form-group">{{ form.submit(class="btn btn-primary") }}</div>
  </form>
</div>

{% endblock content %}

devopcollab/templates/index.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <h1>DevOps Request Management</h1>
  {% if current_user.is_authenticated %}
  <p>Welcome, {{current_user.username}}!</p>
  <p>
    Before you create any request, please make sure you have read
    <a
      href="#"
      >this</a
    >
    wiki page.
  </p>
  {% else %}
  <p>Welcome, you need to login or register to create request.</p>
  {% endif %} {% if current_user.is_authenticated and current_user.is_admin%}
  <div class="col text-right">
    <button type="button" id="update_repos" class="btn btn-success mybutton">
      Download Table
    </button>
  </div>
  {% endif %}
</div>

<div class="container">
  {# Go through each blog post #}

  <table id="data" class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Created By</th>
        <th>Request Time</th>
        <th>Request Title</th>
        <th>Status</th>
        <th>DevOps Effort(h)</th>
        <th>DevOps Owner</th>
      </tr>
    </thead>
    <tbody>
      {% for post in blog_posts.items %}
      <tr>
        <td>{{ post.author.username }}</td>
        <td>{{ post.date.strftime('%Y-%m-%d-%H:%M:%S') }}</td>
        <td>
          <a
            class="card-title"
            href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}"
            >{{ post.title }}</a
          >
        </td>
        <td>{{post.status}}</td>
        <td>{{ post.effort_hour }}</td>
        <td>{{post.devops_onwer}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% endblock %} {% block scripts %}
  <script>
    $(document).ready(function () {
      $("#data").DataTable({
        order: [[1, "desc"]],
        columns: [
          null,
          { searchable: false },
          { orderable: false },
          null,
          { searchable: false },
          null,
        ],
      });
    });
  </script>
  {% endblock %}
</div>

devopcollab/templates/info.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <h1>devops Request Process</h1>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
    non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
</div>

{% endblock %}

devopcollab/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">

<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    <div class="form-group">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {{ form.email(class="form-control",placeholder="Enter email") }}
            <small id="emailHelp" class="form-text text-muted">Your Email.</small>
        </div>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control",type="password",placeholder="Password") }}

            <small id="emailHelp" class="form-text text-muted">Your password is hashed to store.</small>
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </div>
</form>
</div>>
{% endblock %}

devopcollab/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    <div class="form-group">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {{ form.email(class="form-control",placeholder="Enter Your Email") }}
    </div>
    <div class="form-group">
    {{ form.username.label(class="form-control-label") }}
    {{ form.username(class="form-control",placeholder="FirstName.SecondName") }}
    </div>
    <div class="form-group">
    {{ form.password.label(class="form-control-label") }}
    {{ form.password(class="form-control",type="password",placeholder="Password will be hashed to store") }}
    </div>
    <div class="form-group">
    {{ form.pass_confirm.label(class="form-control-label") }}
    {{ form.pass_confirm(class="form-control",type="password",placeholder="Password will be hashed to store") }}
    </div>
    <div class="form-group">
    {{ form.submit(class="btn btn-primary") }}
    </div>
    </div>
</form>
</div>
{% endblock %}

devopcollab/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for post in blog_posts.items %}

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>

{% endfor %}


</div>


{% endblock content %}